### ISSUE TITLE
For react 18, <RouteProvider> needs to be above react's <StrictMode>

### ISSUE THREAD

**Issue by awdyson** [typehero/type-route#102]
If it isn't, URL updates (including `route().link`) won't trigger view updates.
Not sure if this is a documentation change issue or a revamp.

Here's some working code though:
``` tsx
const root = createRoot(document.getElementById('app') as HTMLElement);

function App() {
  return (
    <RouteProvider>
      <StrictMode>
        // other providers and content
      </StrictMode>
    </RouteProvider>
  );
}

root.render(<App />);
```
If I were you, I'd leave this open for a while, even if you update the docs.
Issues are generally the first place I look if something is funky 😛 

Also, this seems ominous... https://github.com/facebook/react/issues/21674#issuecomment-990707432

**Comment by bradenhs** [comment]
Thanks for bringing this up! I did some testing on experimental builds of react a while back but haven't tried out the 18 release yet with Type Route. I'll do that soon.

**Comment by bradenhs** [comment]
This should be fixed in https://github.com/typehero/type-route/releases/tag/0.7.0. Thanks for the report!
