### ISSUE TITLE
Just some feedback

### ISSUE THREAD

**Issue by elderapo** [typehero/type-route#18]
Hey, I just found this library and it seems solid! I love strong type safety and simplicity. Good job!

There are a few things though:

1. There is no `type-route` `Provider/Consumer`. I am not entirely sure what are the use cases where someone might need 2 router instances in the same app (maybe in electron with multiple windows?) but it just doesn't feel "reacty".

2. The definition of route parameters seems a little hacky in my opinion. What I mean is why API with options in strings like this:

```ts
defineRoute(
  {
    page: "query.param.number.optional",
    userId: "path.param.string"
  },
  params => `/user/${params.userId}`
);
```

instead of something like:

```ts
defineRoute({
  path: params => `/user/${params.userId}`,
  params: {
    query: {
      page: {
        type: "number",
        optional: true
      }
    },
    path: {
      userId: {
        type: "string",
      }
    }
  }
});
```

I guess the current approach is a little bit shorter but harder to manipulate (dynamic routing based on some conditions) :smiley:.

3. What would be the recommended way of handling layout components? It's pretty common to see that most of the pages have the following structure: `header`, `dynamic-content` (based on route) and `footer`. In `react-router` it's possible to create such flows in a way that for common pages (those who all share `header`, `footer`) `header` and `footer` components don't get dismounted on route changes.

**Comment by bradenhs** [comment]
Thanks for the great feedback @elderapo! I updated the docs with a couple new pages that may address points 1 and 3 (see https://www.type-route.org/docs/guides/route-components and https://www.type-route.org/docs/guides/page-layout). If those docs don't quite answer your questions feel free to follow up here with any additional thoughts/questions you have.

As to point 2: less verbosity was definitely a goal behind the API decisions being made but I do see your point about how that part of the API might appear hacky. Initially, I did consider providing some enum like object from Type Route to avoid those string literals but TypeScript's great support for string literals convinced me that it wasn't necessary. I am curious what exactly you mean by this though:

> I guess the current approach is a little bit shorter but harder to manipulate (dynamic routing based on some conditions)

It sounds like embedded in there may be some use case I don't fully understand. Could you elaborate?

**Comment by elderapo** [comment]
Thanks for updating the docs! Now 1/3 are crystal clear.

Regarding 2). It's a rare scenario but sometimes you might want to customize routes based on config provided from the API. A simplified example:

```ts
// { key: string, type: "string"/"number", optional: true/false }
const userRouteOptions = await fetchUserRouteOptions();

defineRoute(
    {
        [userRouteOptions.key]: `query.param.${userRouteOptions.type}.${userRouteOptions.optional ? 'optional': "required"}`,
    },
    params => `/user`
);

// vs 

defineRoute({
    url: () => `/user`,
    params: {
        query: {
            [userRouteOptions.key]: {
                type: userRouteOptions.type,
                optional: userRouteOptions.optional
            }
        }
    }
});
```

But as I said... It's a pretty rare scenario so it might not be worth changing.

**Comment by bradenhs** [comment]
Yeah - likely a rare scenario but if you come up with a specific example I'd be interested in hearing it. Introducing dynamic route _definitions_ as you suggested would be hard to design a type safe api around. Since the type of `key` is a string, there wouldn't be a specific property name you'd be able to access elsewhere in your code in a type safe way. The key is to think of these route definitions as TypeScript types. These types are inferred from the runtime code but some of the same challenges you'd run into trying to make a compile time type dynamic would be encountered here as well. Does that make sense?

**Comment by elderapo** [comment]
### 1. Route alias

Is it possible to somehow alias routes? Let's say some app's legacy API had route `/user/{userId}`:

```ts
const { routes, listen, getCurrentRoute } = createRouter({
  user: defineRoute(
    {
      userId: "path.param.number"
    },
    params => `/user/${params.userId}`
  )
});
```

but for any reason now it has to be `/users/{userId}`. Both of those endpoints are supposed to work and render the same component:

```ts
function App() {
  const [route, setRoute] = useState(getCurrentRoute());

  useEffect(() => {
    const removeListener = listen(nextRoute => {
      setRoute(nextRoute);
    });

    return removeListener;
  }, []);

  if (route.name === routes.user.name) {
    return <UserPage userId={route.params.userId} />;
  }

  return <div>Not Found</div>;
}
```

Ideally change like this wouldn't require any change in `App` component.
Don't think it's achievable using `route.extend(...)` because it appends extension at the end of the route. Maybe something like this:

```ts
const userRoute = defineRoute(
  {
    userId: "path.param.number"
  },
  params => `/user/${params.userId}`
);

const { routes, listen, getCurrentRoute } = createRouter({
  user: userRoute,
  users: userRoute.alias(params => `/users/${params.userId}`)
});
```

`routes.users` type could be something like:

```ts
RouteAlias<
  "users",
  RouteDefinition<
    "user",
    {
      userId: "path.param.number";
    }
  >
>
```
so `<a {...routes.users.link({ userId: 123 })}>user 123</a>` would point to `/users/123` but there wouldn't be need to update `App` component to handle aliased declaration like:

```ts
if (route.name === routes.user.name || route.name === routes.users.name) {
  return <UserPage userId={route.params.userId} />;
}
```

### 2. Simple ("static") route redirection

Similar case but instead of aliases we'd want to redirect old routes to new ones. [There](https://www.type-route.org/docs/guides/redirects) is already a way of doing that (for the sake of example I will call this way `dynamic`). This `dynamic` way works but requires a lot of code. I believe it is perfect in case you'd want to check if some user exists before changing the route to `/user/{someUserId}`. But for the case where we'd want just backward URL compability without too much boilerplate `static` way would be much cleaner.

```ts
const usersRoute = defineRoute(
  {
    userId: "path.param.number"
  },
  params => `/users/${params.userId}`
);

const { routes, listen, getCurrentRoute } = createRouter({
  user: usersRoute.redirectFrom(params => `/user/${params.userId}`), // not sure about the method name...
  users: usersRoute
});
```

Now when users clicks on the URL from the external source `http://example.com/user/123` he would get redirected to `http://example.com/users/123`.

**Comment by bradenhs** [comment]
Hmm... I like the ideas but am unsure of the exact API. I hesitate, for instance, introducing an API like the one you suggested for handling redirection that would work for some cases but not all. There are certainly some improvements that can be made though, and, to your point, there is some boilerplate that could be eliminated with a better API around some of these use cases. I really appreciate the feedback! I'm going to keep thinking on this and will definitely ping you if I have any ideas for an updated API or just improved docs.

**Comment by liady** [comment]
What about:
```js
defineRoute({
    query: {
      page: "number.optional",
      title: "string.optional",
    },
    path: {
      userId: "string"
    }
  },
  p => `/user/${p.userId}`
);
```

**Comment by elderapo** [comment]
@bradenhs, I see a lot of cool changes going on in https://github.com/type-route/type-route/pull/35. Have you by any chance thought about simpler API for redirections? I often need to redirect "index" routes to specified main routes ex:

```ts
const account = defineRoute("/account");

createRouter({
  account, // `/account` should automatically redirect to `/account/overview`
  accountOverview: account.extend("/overview"),
  accountSomething: account.extend("/something"),
  accountSettings: account.extend("/settings"),
});
```

Right now this has to be done from `listen` in `useEffect` - it works but doesn't feel right (if you change routing you need to find redirection code etc...). I'd be nice if it was possible to encapsulate whole routing logic within `createRouter` configuration. I remember that my previous suggestion for the API would not cover all the cases. What about something like this:

```ts
const account = defineRoute("/account");
const accountOverview = account.extend("/overview");

createRouter({
  account: account.redirectTo(accountOverview),
  accountOverview,
  accountSomething: account.extend("/something"),
  accountSettings: account.extend("/settings"),
});
```

**Comment by bradenhs** [comment]
A simpler API for redirections has been in the back of my mind. Until now I haven't really known how that simpler API would really work though. There are some more fairly significant changes (on top of the already significant changes) coming to `@next` soon and I _think_ an API for redirects/aliases should fit into that relatively nicely. I'll make sure to ping you when it's ready for a look.

**Comment by bradenhs** [comment]
Hey @elderapo if you have some time I'd appreciate any feedback you have on this: https://codesandbox.io/s/7mhbe?module=src/playground.tsx. To support simple redirect/alias use cases I'm thinking about expanding the defineRoute api to accept an _array_ of strings in addition to a single string value. The first item in the array is the primary path for that route and is used by the application when navigating to that route. The route can also be matched against subsequent array items. When the route is matched against a non primary path the url is immediately changed to the primary path (replacing the current browser history entry). So the above example with this api would look something like the following:

```ts
const account = defineRoute("/account");

createRouter({
  accountOverview: account.extend(["/overview", "/"]),
  accountSettings: account.extend("/settings"),
});
```

In the above case `/account/overview` and `/account` would both match the `accountOverview` route. When there are non-uniform parameters in different routes this api will not be sufficient but the current method of manually doing redirects when the route changes should still work for those more complex use cases.

**Comment by bradenhs** [comment]
Here's a working example of this new api if you'd like to play around with it: https://codesandbox.io/s/z5u2t?module=src/playground.tsx

**Comment by elderapo** [comment]
This definitely works but IMO array approach feels a little bit obscure.

I checked out the playground without reading your previous message and my instant thoughts were: aliases, cool! But.... do both of the URLs remain in the browser URL bar or does one get redirected to the other?

Now after reading your previous message/testing it, I know it gets redirected to the first one. Maybe the configuration object instead of just an array would work here?

```ts
export const { routes, session, listen } = createRouter({
  home: defineRoute({
    path: "/dashboard",
    aliases: ["/", "/old-dashboard"]
  }),
  account: account.extend({
    route: "/overview",
    aliases: ["/"]
  }),
  user: defineRoute(
    {
      userId: param.path.string,
    },
    (x) => ({
      route: `/user/${x.userId}`,
      aliases: [`/users/${x.userId}`]
    })
  ),
});
```

**Comment by bradenhs** [comment]
I see your point. It would certainly be more clear to explicitly specify that certain paths were aliases to the main path. I think this issue could be solved with documentation but _will_ give this some serious thought. Thanks for raising the concern. Besides exactly how the API looks are there any other concerns you have with this approach?

**Comment by elderapo** [comment]
> Besides exactly how the API looks are there any other concerns you have with this approach?

Nope, all seems good! :+1:

**Comment by bradenhs** [comment]
I think most of the points here are covered in the latest release `0.4.0`. Feel free to reopen though if something isn't fully addressed.
