### ISSUE TITLE
[BUG] Link onClick error

### ISSUE THREAD

**Issue by elderapo** [typehero/type-route#38]
The following code causes an error:

```ts
routes.signIn.link({
  onClick: () => {},
});
```

```bash
validate.js:32 Uncaught Friendly Type Route Error Here 😁: 

Error invoking `link`

Hope this helps:

Got unexpected key `onClick` in params object

Usage:

link(params?: Parameters): { href: string, onClick: (event?: { preventDefault?: () => void }) => void }
```

However, typescript tells me that the link can accept `onClick` event handler as an argument.

In my case, I want to call an additional function when specific link is being clicked. My current workaround is:
```ts
<A
  {...routes.signIn.link({})}
  onClickCapture={e => {
    // ...
  }}
>
  NOT YOU?
</A>
```

**Comment by bradenhs** [comment]
Which version of Type Route are you using? I'm surprised TypeScript is telling you it can accept `onClick` as an argument to link. You could approach this with something along the lines of this:

```tsx
<a
  href={routes.signIn.href()}
  onClick={e => {
    e.preventDefault();
    yourOtherFunction();
    routes.signIn.push();
   }
>
  Sign In
</a>
```

If that doesn't work could you share a codesandbox that demonstrates the issue?

**Comment by elderapo** [comment]
Package.json says the version is `^0.3.6`.

**Comment by bradenhs** [comment]
![Screen Shot 2020-06-11 at 9 00 36 AM](https://user-images.githubusercontent.com/22484684/84388441-98930b00-abc2-11ea-9d60-845c00549ad5.png)

It looks like maybe you're misreading this and mixing up what the function returns with what parameters it accepts? There _is_ a problem here though. The `link` function should show a TypeScript error when trying to pass in a value it doesn't accept which it is not showing here. This is a little more misleading than it would have otherwise been since there isn't a ts error there. The good news is that this is fixed in `type-route@next`. One of the changes in `type-route@next` is how routes are built. Instead of calling `routes.home.href(params)` and `routes.home.push(params)` you'll call `routes.home(params)` which returns an object with `href` and `push` on it. This should make composing these in a custom way easier. The very much under construction `@next` docs have a page on this: https://typehero.org/type-route/docs/guides/custom-link-behavior. If you have a moment to review that and share your thoughts that'd be super helpful!

**Comment by elderapo** [comment]
Ok, so that was just typings error.

---

Regarding the new API. What is the reasoning behind changing `routes.home.link(params)` to `routes.home(params).link`? I personally find:

```tsx
<a {...routes.home.link(params)}>home</a>
```

cleaner/more straightforward than:

```tsx
<a {...routes.home(params).link}>home</a>
```
---

Creating custom `Link` component works (with old and new api) but it's not always feasible/ergonomic. For example: if you want to use a link component from some external library you will have to wrap that component into your own...

In my opinion it would be better if it was possible to specify `onClick` similarly to what I was initially trying to do:

```tsx
<a
  {...routes.home.link(params, {
    onClick: e => console.log("going home..."),
  })}
>
  home
</a>
// or
<a
  {...routes.home.link({
    params,
    onClick: e => console.log("going home..."),
  })}
>
  home
</a>
```
This adds a little bit of complexity (arguments passed to `link` function can have many "shapes") but completely removes the need of creating custom link wrappers and should work with all link components that utilize `href` & `onClick` props.

**Comment by bradenhs** [comment]
I did give some serious consideration to providing an API like you've mentioned. As I tested how it would work with different use cases, however, it became clear it wasn't a silver bullet. In scenarios where you want to perform some action along side the route update it works quite well. But, there may be situations where you want to provide custom code _before_ pushing the new route and then maybe only do so conditionally. When running React in concurrent mode you may want to wrap the route update in the `startTransition` function to ensure any resulting calls to `setState` are part of the transition. Given these considerations I've landed on the recommendation to build out a custom Link component looking something like this when supporting more complex use cases is necessary:

```tsx
import React from "react";
import { Route, preventDefaultClickBehavior } from "type-route";
import { routes } from "./router";

type Props = {
  to: Route<typeof routes>
  children?: React.ReactNode;
}

function Link(props: Props) {
  const { to, children } = props;

  return (
    <a
      href={to.href}
      onClick={event => {
        if (preventDefaultLinkClickBehavior(event)) {
          to.push();
        }
      }}
    >
      {children}
    </a>
  )
}
```

Spreading the link object `<a {...routes.home().link>Home</a>` should still work for simple cases. With this recommendation for more complex use cases I feel like there's less of a chance of a use case not being expressible with the recommended pattern.

Recognizing the need to give the user ways to more easily build abstractions on top of Type Route (as in the above example) led me down the path of putting `link` / `push` / `replace` / `href` on the route object. Building a `Link` component would be more difficult with parameterized versions of `link` / `push` / `replace` / `href`. Correlating the route and parameters in a type safe way in the Props of the Link component would involve some ugly TypeScript gymnastics that would be great to keep out of user land code. That being said I too, at first glance, like `routes.home.link()` more than `route.home().link`. But I think its a worthwhile tradeoff. Hopefully that gives you a little more context! And `@next` hasn't landed yet so there's still room for changes.

**Comment by bradenhs** [comment]
Going to close this since the behavior doesn't appear to be a bug. Happy to continue discussing different approaches to the API though!

**Comment by bradenhs** [comment]
@elderapo if you have any feedback I just opened https://github.com/typehero/type-route/pull/39 which has some experimentation around making Type Route more tightly coupled to React.
