### ISSUE TITLE
Preserve query strings across routes

### ISSUE THREAD

**Issue by mscolnick** [typehero/type-route#50]
Is there good solution to preserve the query-string between routes?

For example, say we start at:
```
`/foo?utm_source=blah`
```
then when navigating to `/bar` by either `routes.bar().push()` or `<a {...routes.bar().link} />`. we lose the query param `utm_source`

**Comment by bradenhs** [comment]
Hi @mscolnick thanks for the question! To ensure every route has the `utm_source` query param I'd recommend using the route extension API.

```tsx
const base = defineRoute(
  {
    utm_source: param.query.optional.string
  },
  () => "/"
);

const { RouteProvider, useRoute, routes } = createRouter({
  foo: base.extend("/foo"),
  bar: base.extend("/bar")
});
```

Here are some docs for the `extend` API: https://typehero.org/type-route/docs/api-reference/route-definition/extend. With this approach, however, you'd still need to explicitly pass `utm_source` to every route. Something like:

```tsx
const route = useRoute();
return <a {...routes.bar({ utm_source: route.params.utm_source }).link}/>
```

With some gymnastics you could create a helper that would do this for you. It's not perfect but depending on your exact needs it may be worth it:

```tsx
function useRouteWithUtmSource(route: Route<typeof routes>) {
  const currentRoute = useRoute();

  if (route.name === false || currentRoute.name === false) {
    // This approach unfortunately doesn't handle 404 routes super well since route parameters are not passed to those.
    return route;
  }
  
  return routes[route.name]({ ...(route.params as any), utm_source: currentRoute.params.utm_source });
}

function Link() {
  const route = useRouteWithUtmSource(routes.foo());
  return <a {...route.link}>Foo</a>;
}
```

**Comment by mscolnick** [comment]
thank you @bradenhs, this works!
