### ISSUE TITLE
[Docs] Best practice for authenticating a route

### ISSUE THREAD

**Issue by mscolnick** [typehero/type-route#51]
It would be cool to have a recipe or best practice for wrapping a route in auth (making it protected). It is fairly easy to do this in the react component lifecycle, similar to how it is suggested in react-router, but i'm sure there is a better way to do it with this library.

Here is the react-router example: https://reactrouter.com/web/example/auth-workflow

```jsx
// A wrapper for <Route> that redirects to the login
// screen if you're not yet authenticated.
function PrivateRoute({ children, ...rest }) {
  return (
    <Route
      {...rest}
      render={({ location }) =>
        fakeAuth.isAuthenticated ? (
          children
        ) : (
          <Redirect
            to={{
              pathname: "/login",
              state: { from: location }
            }}
          />
        )
      }
    />
  );
}
```

**Comment by bradenhs** [comment]
Thanks for the question @mscolnick and sorry for the slow reply!  I like Kent Dodd's recommendation for this which removes the need for a client-side redirect: https://kentcdodds.com/blog/authentication-in-react-applications/

If for some reason that doesn't work the equivalent in Type Route would look something like this.

```tsx
function PrivateRoute({ children }) {
  const auth = useAuth();
  const route = useRoute();

  useEffect(() => {
    if (auth === null) {
      routes.login.push({ fromHref: route.href });
    }
  }, [auth, route]);

  return auth === null ? "Redirecting to login..." : children;
}
```

Then after you've logged in you can do something like this to go back to the route you were redirected from:

```tsx
session.replace({ href: route.params.fromHref });
```

I hesitate to put this technique in the docs b/c I prefer the strategy outlined in the linked article. Does that linked article work for you? If not, would you mind explaining? I could very well be missing something.

**Comment by mscolnick** [comment]
The example / linked article is great - and a similar approach I ended up going with. Your hesitation to add to the docs is valid, feel free to close this out.

Thanks again
