### ISSUE TITLE
We made a plugin to enable type-route to work with github pages

### ISSUE THREAD

**Issue by garronej** [typehero/type-route#63]
Hi @bradenhs,
I just wanted to show you [what](https://github.com/garronej/github-pages-plugin-for-type-route) a friend and I did yesterday to be able to deploy `create-react-app` that uses `type-route` on github pages.  
The problem is that github pages has no configuration to enable single pages application.
If you GET `https://my-domain.com/a/b/foo` github page will serve `a/b/foo.html` when in reality we would like that, regardless of the url path, it's always the `index.html` that is served.  
The workaround is to copy the content of `index.html` into a `404.html` file, it works but it's very bad for SEO.  

What we did is we made a build tool that scan the route declaration of a project and copy the index.html everywhere there is a path before deploying. 

![image](https://user-images.githubusercontent.com/6702424/100515459-b65a2980-317c-11eb-9884-a53a0fe3fdbf.png)

![image](https://user-images.githubusercontent.com/6702424/100515424-7004ca80-317c-11eb-9d7d-c371de576c11.png)

![image](https://user-images.githubusercontent.com/6702424/100515795-ec001200-317e-11eb-9b44-1462addf2478.png)

Then when we run `yarn deploy` this get generated for us after the build: 
![image](https://user-images.githubusercontent.com/6702424/100515450-a04c6900-317c-11eb-8153-a5a278ae58cd.png)

All this files are copies of `index.html` generated by the tool:
```json
[
    "auteur.html",
    "evenements.html",
    "naturalisme.html",
    "naturalisme/antilles.html",
    "naturalisme/france.html",
    "naturalisme/ouset-canadiens.html",
    "naturalisme/reunion.html",
    "portrait.html",
    "404.html"
]
```

result: TADAAAA! No 404 anymore 🥳 

![image](https://user-images.githubusercontent.com/6702424/100515655-fcfc5380-317d-11eb-8f52-7f207e1a24ce.png)

First project on to which we set the plugin up: https://github.com/thieryw/theo-tz
And it's deployment: http://thieryw.github.io/theo-tz

Unfortunately this wont work with pages with dynamic path like `https://myWebsite.com/bob/orders` but this is not the kind of websites we would like to deploy on gh pages anyway.  

Other sad point is we had to use the `~internal` API so it is implementation dependent and can break with future version of type route.  
![image](https://user-images.githubusercontent.com/6702424/100515731-8c096b80-317e-11eb-9f34-c2745d814740.png)

Voilà. I hope you will be pleased to know that we like your lib so much that we invest some time writing a plugin for it.

Cheers.

**Comment by bradenhs** [comment]
Cool! Thanks for sharing. This is clever. Here's another project you may want to consider playing around with: https://github.com/stereobooster/react-snap. I've used it before to accomplish something similar to this.
