### ISSUE TITLE
dynamic query parameters support

### ISSUE THREAD

**Issue by garronej** [typehero/type-route#75]
Hi @bradenhs,

What is for you the best approach to describe query parameters that can't be known in advance.  

For example I would like to have an url like that:
`https://datalab.sspcloud.fr/launcher/datascience/tensorflow?gpu=2&cpu=0.2`  
but `gpu` and `cpu` is not something that I can declare in the types.  

For now what I do is:  

![image](https://user-images.githubusercontent.com/6702424/119243723-c53cfa00-bb69-11eb-9298-5d05376cf136.png)

But my url look like that witch is not ideal...
`http://datalab.sspcloud.fr/launcher/datascience/tensorflow?p=gpu%3D2%2Ccpu%3D0.2`

**Comment by bradenhs** [comment]
Unfortunately there isn't a great way to make the names of query params dynamic. It is possible though. See: https://typehero.org/type-route/docs/guides/custom-query-string. The last half of that section describes how you could write your own query string parser with custom behavior. But if that's not absolutely necessary I'd recommend sticking with the simpler work around you're using now. Depending on what kind of values end up in the "p" parameter you might be able to disable url escaping for that section which could make the url more human readable.

**Comment by garronej** [comment]
Thanks for your reply!  
Pretty URL is too much of a selling point for our app, we can't settle on that.
I ended up using a combination of `ValueSerializer` and `QueryStringSerializer`, I hope future maintainers won't be too mystified by the solution ([here](https://github.com/InseeFrLab/onyxia-ui/blob/3409bd4584324d1af5c0742d6ddb0c98f337c770/src/app/routes/router.ts#L51) and [here](https://github.com/InseeFrLab/onyxia-ui/blob/master/src/app/routes/formFieldsQueryParameters.ts)).  
What bothers me the most is that my solution breaks the separation of concern. The `QueryStringSerializer` being global I have no way of knowing for which page I am serialising/parsin queries parameters so I am doing some unsafe assertion on the keys.  

Also I was a bit frustrated by the fact that [here](https://github.com/typehero/type-route/blob/3eff05d42c847fea259b392a5a6c17192c5bd417/src/createRouteBuilder.ts#L31) you check the existence of the propertiy by doing `if( !(paramKey  in routeDef["~internal"].params) )` instead of `if( routeDef["~internal"].params[paramKey] === undefined )`, it pvevented me from implementing a solution using [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 😞   

Anyway, still a fan and strong supporter of type route. 👍🏻   

Best regards

**Comment by bradenhs** [comment]
Thanks for bringing up another use case here. Perhaps one day I'll come up with a better solution for this type of scenario.

**Comment by bradenhs** [comment]
Also I believe this could help you out if you want to use `Proxy` with `in`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/has

**Comment by garronej** [comment]
> Also I believe this could help you out if you want to use `Proxy` with `in`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/has

Wonderfull, I didn't know about that! I wish I knew it before.
