### ISSUE TITLE
Obtain route by providing string url

### ISSUE THREAD

**Issue by elderapo** [typehero/type-route#85]
Would be nice if it was possible to get an instance of the route from the router by providing it with the string URL. My use case is a chat app where users can potentially post links. When rendering messages I find all the links, replace them with custom link components that on click either:
- if it's a link to the external website display "Warning, you're leaving the website... YES/NO"
- if it's a link to the page on the current website (basically when `window.location.hostname` matches the `hostname` from the link) I'd like to just redirect (ex. `route.replace()`) the user to that page without website reload.

I suggest exposing function (`pathnameToRoute`?) on the router instance that either takes `pathname` (ex. `window.location.pathname`) and returns `Route | null`.

I am pretty sure this functionality is already implemented and just needs to be exposed ;)

**Comment by elderapo** [comment]
After digging a little bit, seems like it's already possible with `router.session.replace(url.pathname)`.

**Comment by bradenhs** [comment]
> After digging a little bit, seems like it's already possible with router.session.replace(url.pathname).

Yep, that's how I'd go about it!
